# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VTMLpRQWlDzLCDcM39p46ZEAqDn4h3m
"""

import pandas as pd
from geopy.geocoders import Nominatim
import os
from concurrent.futures import ThreadPoolExecutor

# Inicjalizacja geokodera
geolocator = Nominatim(user_agent="my_geocoder")

# Ścieżka do folderu z plikami CSV
folder_path = '/ścieżka/do/folderu/'

# Funkcja do przetwarzania pojedynczego pliku CSV
def process_csv(file_path):
    # Wczytanie danych z pliku CSV
    df = pd.read_csv(file_path)

    # Konwersja adresów na współrzędne geograficzne
    df['Wspolrzedne'] = df['Adres'].apply(geolocator.geocode)

    # Wyodrębnienie szerokości i długości geograficznej z obiektów współrzędnych
    df['SzerokoscGeograficzna'] = df['Wspolrzedne'].apply(lambda x: x.latitude if x else None)
    df['DlugoscGeograficzna'] = df['Wspolrzedne'].apply(lambda x: x.longitude if x else None)

    # Usunięcie kolumny Wspolrzedne, jeśli nie jest już potrzebna
    df.drop('Wspolrzedne', axis=1, inplace=True)

    # Zapisanie zaktualizowanych danych do pliku CSV
    df.to_csv(file_path, index=False)

# Pobranie listy plików CSV z folderu
csv_files = [os.path.join(folder_path, filename) for filename in os.listdir(folder_path) if filename.endswith('.csv')]

# Wykorzystanie ThreadPoolExecutor do równoległego przetwarzania plików
with ThreadPoolExecutor() as executor:
    executor.map(process_csv, csv_files)

